name=(input("what's your name? "))
family=(input("what's your family? "))
nomrehDars1=int(input("please insert nomrehDars1: "))
n1=open("project/Darse1.py","a")
n1.write(f"{name} {family} = {nomrehDars1}\n")
n1.close()
nomrehDars2=int(input("please insert nomrehDars2: "))
n2=open("project/Darse2.py","a")
n2.write(f"{name} {family} = {nomrehDars2}\n")
n2.close()
nomrehDars3=int(input("please insert nomrehDars3: "))
n3=open("project/Darse3.py","a")
n3.write(f"{name} {family} = {nomrehDars3}\n ")
n3.close()
nomrehDars4=int(input("please insert nomrehDars4: "))
n4=open("project/Darse4.py","a")
n4.write(f"{name} {family} = {nomrehDars4}\n")
n4.close()
nomrehDars5=int(input("please insert nomrehDars5: "))
n5=open("project/Darse5.py","a")
n5.write(f"{name} {family} = {nomrehDars5}\n")
n5.close()
f=open(f"project/{name}{family}.py","w")
f.write(f"your avrage is :{(nomrehDars1+nomrehDars2+nomrehDars3+nomrehDars4+nomrehDars5)/5}")
f.write(f"\nnomrehDars1 is :{nomrehDars1}\nnomrehDars2 is :{nomrehDars2}\nnomrehDars3 is :{nomrehDars3}\nnomrehDars4 is :{nomrehDars4}\nnomrehDars5 is :{nomrehDars5}")
f.close()


